"""init database

Revision ID: a7acfdd362dc
Revises: 
Create Date: 2018-04-23 20:18:57.920490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7acfdd362dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('work_years', sa.SmallInteger(), nullable=True),
    sa.Column('resume_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=512), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('oneword_profile', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo')
    )
    op.create_table('job',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=False),
    sa.Column('salary_max', sa.Integer(), nullable=False),
    sa.Column('experience_requirement', sa.String(length=1024), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('company_msg', sa.String(length=1024), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('job_requirement', sa.String(length=1024), nullable=True),
    sa.Column('job_description', sa.String(length=1024), nullable=True),
    sa.Column('job_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('company')
    op.drop_table('user')
    # ### end Alembic commands ###
